apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ec-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url : "true"
spec:
  rules:
    - host: express-cluster.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ec-svc
                port:
                  number: 3000
